name: test_tl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  awesome_dialog: ^3.2.1
  easy_stepper: ^0.8.5+1
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  flutter_native_splash: ^2.4.1
  flutter_smart_dialog: ^4.9.8+1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  mailer: ^6.1.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  quickalert: ^1.1.0
  shared_preferences: ^2.3.2
  syncfusion_flutter_pdf: ^26.2.14
  syncfusion_flutter_pdfviewer: ^26.2.14
  toastification: ^2.2.0
cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
